services:
  # Backend service
  - type: web
    name: waybill-extractor-backend
    env: python
    buildCommand: cd backend && chmod +x build.sh && ./build.sh
    startCommand: cd backend && gunicorn waybill_project.asgi:application --bind 0.0.0.0:$PORT --workers 4 --worker-class uvicorn.workers.UvicornWorker --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: CORS_ALLOW_ALL_ORIGINS
        value: true
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: AWS_REGION
        value: us-east-1
      - key: MISTRAL_API_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false

  # Frontend service
  - type: web
    name: waybill-extractor-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm install -g serve && serve -s build -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: REACT_APP_API_BASE_URL
        value: https://waybill-extractor-backend.onrender.com/api
