# Generated by Django 5.1.7 on 2025-03-17 02:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Extraction Model',
                'verbose_name_plural': 'Extraction Models',
            },
        ),
        migrations.CreateModel(
            name='WaybillImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='waybills/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('extraction_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waybill.extractionmodel')),
            ],
            options={
                'verbose_name': 'Waybill Image',
                'verbose_name_plural': 'Waybill Images',
            },
        ),
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_data', models.JSONField()),
                ('extracted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('waybill_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='waybill.waybillimage')),
            ],
            options={
                'verbose_name': 'Extracted Data',
                'verbose_name_plural': 'Extracted Data',
            },
        ),
    ]
